import json

class NotebookGenerator:
    """Service to generate pre-filled Colab/Kaggle notebooks."""
    
    @staticmethod
    def generate_colab_notebook(config: dict):
        """Generates a .ipynb file content as a string."""
        model_name = config.get("model_name", "distilgpt2")
        epochs = config.get("epochs", 3)
        lr = config.get("learning_rate", 2e-4)
        
        cells = [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# FineTuneStudio: Training {model_name}\n",
                    "This notebook was automatically generated by FineTuneStudio. "
                    "Run the cells below to start your training session."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "!pip install -q transformers datasets peft accelerate bitsandbytes\n",
                    "from huggingface_hub import notebook_login\n",
                    "notebook_login()"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import torch\n",
                    "from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer\n\n",
                    f"model_id = \"{model_name}\"\n",
                    "tokenizer = AutoTokenizer.from_pretrained(model_id)\n",
                    "model = AutoModelForCausalLM.from_pretrained(model_id, load_in_4bit=True, device_map='auto')\n\n",
                    "# Hyperparameters from FineTuneStudio\n",
                    f"training_args = TrainingArguments(\n",
                    f"    output_dir='./results',\n",
                    f"    num_train_epochs={epochs},\n",
                    f"    learning_rate={lr},\n",
                    "    per_device_train_batch_size=4,\n",
                    "    logging_steps=10,\n",
                    ")\n\n",
                    "print(\"🚀 Ready to train!\")"
                ]
            }
        ]
        
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                "language_info": {"name": "python", "version": "3.10.0"}
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }
        
        return json.dumps(notebook, indent=2)
